### ISSUE TITLE
Valeurs négatives

### ISSUE THREAD

**Issue by nyanloutre** [LaBaleineFr/Chalutier#4]
En testant un peu la script avec différentes valeurs je suis tombé sur des valeurs négatives

Ex : 
```
docker run -it --rm chalutier python ./chalutier-cli.py --currencies ETH LTC BCH XRP DASH XCP
{
  "result": {
    "ETH": 0.22221353861459203,
    "LTC": 0.39676140654777137,
    "BCH": 0.21164794782303392,
    "XRP": -0.03521513514226092,
    "DASH": 0.05434358487928241,
    "XCP": 0.15024865727758108
  }
}
```

**Comment by Batalex** [comment]
Merci de ton retour, je vais regarder ça de plus près. C'est un problème d'instabilité numérique lors de la phase d'optimisation je pense.

**Comment by Batalex** [comment]
Je laisse ouvert l'issue au cas où, mais d'une part je n'ai pas réussi à reproduire l'erreur de mon côté, et deuxièmement j'ai fait une amélioration de stabilité, donc à voir si ce problème persiste.
