### ISSUE TITLE
Marche pas en Python 3.4 ?

### ISSUE THREAD

**Issue by bragonznx** [LaBaleineFr/Chalutier#6]
python3.4 chalutier-cli.py --currencies ETH LTC BCH XRP DASH XCP
Traceback (most recent call last):
  File "chalutier-cli.py", line 18, in <module>
    print(json.dumps(optimiz.optimiz(args['currencies'], debug), indent=2))
  File "/home/bragon/crypto/Chalutier/optimiz.py", line 132, in optimiz
    executor = ThreadPoolExecutor()
TypeError: __init__() missing 1 required positional argument: 'max_workers'

**Comment by Batalex** [comment]
Merci pour la remontée du problème, c'est réglé et testé (sur container) !
